export type WorkspaceEventType =
  | "BOOKING_CREATED"
  | "BOOKING_CANCELLED"
  | "BOOKING_COMPLETED"
  | "INVOICE_CREATED"
  | "INVOICE_PAID"
  | "PROJECT_CREATED"
  | "PROJECT_COMPLETED"
  | "CLIENT_CREATED";